spring:
  profiles: lcl
  data:
    mongodb:
      host: allmarket-hml.lojse.mongodb.net
      port: 27017
      database: myFirstDatabase
      username: teste-dev
      password: teste-dev
      repositories:
        enabled: true