project:
  version: '@project.version@'

server:
  port: 8091
  servlet:
    context-path: /clientes

spring:
  application:
    name: MvpClienteJava
  profiles:
    active: lcl

---
spring:
  profiles: lcl
  data:
    mongodb:
      uri: mongodb+srv://${USER}:${PASSWORD}@cluster0.1owfgvr.mongodb.net/mongo?retryWrites=true&w=majority


